### ISSUE TITLE
Wrong type check with undefined.

### ISSUE THREAD

**Issue by malash** [ihtml5/jscalpel#3]
In [this line of code](https://github.com/ihtml5/jscalpel/blob/master/src/index.js#L17) the `typeof result` could never return `undefined` so the condition will always be `false`.

```js
      if (typeof result === undefined) {
        return result;
      }
```

The correct way to check if a value is `undefined` could be like `typeof result === 'undefined'` or `result === 'undefined'`.

BTW, A strict ESLint check is requested for an open source JavaScript project. The [Airbnb one](https://github.com/airbnb/javascript) is a good choice.

**Comment by ihtml5** [comment]
Thank you for your suggestion. This is indeed a bug. I will fix it later. After being free, I will perfect eslint detection and unit testing

**Comment by ihtml5** [comment]
It has been fixed. This uses result === void 0 because [undefined](https://www.zhihu.com/question/52645620) itself may be modified。
